# Generated by Django 4.1.4 on 2023-09-01 22:37

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.upload_to),
        ),
    ]
